---
# Run the compose file as follows
# docker-compose --env-file ./environment-variables.sh -f multi-node-docker-compose.yml up
# docker-compose --env-file ./environment-variables.sh -f multi-node-docker-compose.yml down --remove-orphans
#
version: '2'

networks:
  default:
    name: izzyacademy_multi_streams

services:

  # You can use this to connect to the docker container once it is running
  # docker exec -it debugger /bin/bash
  debugger:
    image: izzyacademy/kafka-base:3.0.0
    hostname: debugger
    container_name: debugger
    entrypoint: [ 'sleep', '48h' ]

  node1:
    image: izzyacademy/kafka:3.0.0
    hostname: node1
    container_name: node1
    ports:
      - "29091:29091"
      - "19091:19091"
      - "9091:9091"
      - "9101:9101"
    environment:
      KAFKA_NODE_ID: '1'
      KAFKA_PROCESS_ROLES: 'controller'
      KAFKA_CLUSTER_ID: "${CLUSTER_ID}"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "${CONTROLLER_QUORUM_VOTERS}"
      KAFKA_LISTENERS: 'PLAINTEXT_HOST://0.0.0.0:29091,CONTROLLER://0.0.0.0:19091,PLAINTEXT://0.0.0.0:9091'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://node1:29091,PLAINTEXT_HOST://node1:9091 # do not include controller socket here
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_LOG_DIRS: "${LOG_DIRS}"

  node2:
    image: izzyacademy/kafka:3.0.0
    hostname: node2
    container_name: node2
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9102:9102"
    environment:
      KAFKA_NODE_ID: '2'
      KAFKA_PROCESS_ROLES: 'broker'
      KAFKA_CLUSTER_ID: "${CLUSTER_ID}"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "${CONTROLLER_QUORUM_VOTERS}"
      KAFKA_LISTENERS: 'PLAINTEXT_HOST://0.0.0.0:29092,CONTROLLER://0.0.0.0:19092,PLAINTEXT://0.0.0.0:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://node2:29092,PLAINTEXT_HOST://node2:9092 # do not include controller socket here
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9102
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_LOG_DIRS: "${LOG_DIRS}"

  node3:
    image: izzyacademy/kafka:3.0.0
    hostname: node3
    container_name: node3
    ports:
      - "29093:29093"
      - "19093:19093"
      - "9093:9093"
      - "9103:9103"
    environment:
      KAFKA_NODE_ID: '3'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CLUSTER_ID: "${CLUSTER_ID}"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "${CONTROLLER_QUORUM_VOTERS}"
      KAFKA_LISTENERS: 'PLAINTEXT_HOST://0.0.0.0:29093,CONTROLLER://0.0.0.0:19093,PLAINTEXT://0.0.0.0:9093'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://node3:29093,PLAINTEXT_HOST://node3:9093 # do not include controller socket here
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9103
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_LOG_DIRS: "${LOG_DIRS}"

  node4:
    image: izzyacademy/kafka:3.0.0
    hostname: node4
    container_name: node4
    ports:
      - "29094:29094"
      - "19094:19094"
      - "9094:9094"
      - "9104:9104"
    environment:
      KAFKA_NODE_ID: '4'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CLUSTER_ID: "${CLUSTER_ID}"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "${CONTROLLER_QUORUM_VOTERS}"
      KAFKA_LISTENERS: 'PLAINTEXT_HOST://0.0.0.0:29094,CONTROLLER://0.0.0.0:19094,PLAINTEXT://0.0.0.0:9094'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://node4:29094,PLAINTEXT_HOST://node4:9094 # do not include controller socket here
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9104
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_LOG_DIRS: "${LOG_DIRS}"
