# Licensed to IzzyAcademy.com under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# IzzyAcademy.com licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
{{- if .Values.kraft.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node2
  namespace: "{{ .Values.infrastructure.namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: node2
    spec:
      containers:
      - image: "izzyacademy/kafka:3.0.0"
        name: node2
        resources:
          requests:
            memory: {{ .Values.broker.brokerMemory }}
            cpu: {{ .Values.broker.brokerCPU }}
          limits:
            memory: {{ .Values.broker.brokerMemory }}
            cpu: {{ .Values.broker.brokerCPU }}
        env:
        - name: KAFKA_NODE_ID
          value: "{{ .Values.kraft.node2Id }}"
        - name: KAFKA_PROCESS_ROLES
          value: {{ .Values.kraft.node2Role }}
        - name: KAFKA_CLUSTER_ID
          value: {{ .Values.kraft.clusterId }}
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: {{ .Values.kraft.controllerQuorumVoters }}
        - name: "KAFKA_LISTENERS"
          value: {{ .Values.kraft.listeners }}
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: {{ .Values.kraft.securityProtocolMap }}
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://node2-internal:29092,PLAINTEXT_HOST://node2-internal:9092"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value:  {{ .Values.kraft.interBrokerListenerName }}
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value:  {{ .Values.kraft.controllerListenerName }}
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "2"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: "3000"
        - name: KAFKA_JMX_PORT
          value: "9101"
        - name: KAFKA_HEAP_OPTS
          value: {{ .Values.broker.brokerHeap }}
        - name: KAFKA_LOG_DIRS
          value: {{ .Values.kraft.logDirs }}
        ports:
        - containerPort: 9092
          name: primary
        - containerPort: 9093
          name: secondary
        - containerPort: 9101
          name: jmxport
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: {{ .Values.broker.failureThreshold }}
        livenessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 15
          failureThreshold: {{ .Values.broker.failureThreshold }}
          periodSeconds: 15
        volumeMounts:
        - name: "node2-volume"
          mountPath: {{ .Values.kraft.logDirs }}
      volumes:
      - name: "node2-volume"
        persistentVolumeClaim:
          claimName: "node2-persistent-storage"

---
# This is the internal load balancer
apiVersion: v1
kind: Service
metadata:
  name: "node2-internal"
  namespace: "{{ .Values.infrastructure.namespace }}"
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: "ClusterIP"
  ports:
  - port: 9092
    protocol: TCP
    name: a
  - port: 19092
    protocol: TCP
    name: b
  - port: 29092
    protocol: TCP
    name: c
  selector:
    app: node2

---
# This is the external load balancer
apiVersion: v1
kind: Service
metadata:
  name: "node2-external"
  namespace: "{{ .Values.infrastructure.namespace }}"
spec:
  type: "NodePort" # Kubernetes will find something between 30000-32767
  ports:
  - port: 9092
    protocol: TCP
    name: a
  - port: 19092
    protocol: TCP
    name: b
  - port: 29092
    protocol: TCP
    name: c
  selector:
    app: node2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "node2-persistent-storage"
  namespace: "{{ .Values.infrastructure.namespace }}"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.infrastructure.storageClass }}
  resources:
    requests:
      storage: 5Gi

{{- end }}